# Generated by Django 3.1.2 on 2020-11-10 05:03

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asistentes',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=80)),
                ('apellido', models.CharField(max_length=80)),
                ('correo', models.CharField(max_length=80)),
                ('codigo', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Eventos',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=80)),
                ('fecha_inicio', models.DateField()),
                ('fecha_final', models.DateField()),
                ('estado', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Inscritos',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=80)),
                ('apellido', models.CharField(max_length=80)),
                ('codigo', models.IntegerField(blank=True, null=True)),
                ('correo', models.CharField(max_length=80)),
                ('paquete', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=80), size=None)),
                ('id_asistente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='public.asistentes')),
            ],
        ),
        migrations.CreateModel(
            name='Paquetes',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('categorizacion', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=80), size=None)),
                ('promociones', models.CharField(max_length=80)),
                ('categoria', models.CharField(max_length=80)),
                ('precio', models.FloatField()),
                ('id_evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='public.eventos')),
            ],
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=80)),
                ('apellido', models.CharField(max_length=80)),
                ('usuario', models.CharField(max_length=80)),
                ('contraseña', models.CharField(max_length=80)),
                ('correo', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Recibo',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=80)),
                ('cantidad', models.IntegerField(blank=True, null=True)),
                ('nro_cuenta', models.IntegerField(blank=True, null=True)),
                ('fecha', models.DateTimeField()),
                ('id_inscrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='public.inscritos')),
            ],
        ),
        migrations.CreateModel(
            name='Preinscritos',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=80)),
                ('apellido', models.CharField(max_length=80)),
                ('codigo', models.IntegerField(blank=True, null=True)),
                ('correo', models.CharField(max_length=80)),
                ('paquete', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=80), size=None)),
                ('id_asistente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='public.asistentes')),
                ('id_paquete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='public.paquetes')),
            ],
        ),
        migrations.AddField(
            model_name='inscritos',
            name='id_paquete',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='public.paquetes'),
        ),
        migrations.CreateModel(
            name='Ingresos',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nro_cuenta', models.IntegerField(blank=True, null=True)),
                ('cantidad', models.IntegerField(blank=True, null=True)),
                ('estado_pago', models.CharField(max_length=80)),
                ('id_evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='public.eventos')),
            ],
        ),
        migrations.CreateModel(
            name='Egresos',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nro_cuenta', models.IntegerField(blank=True, null=True)),
                ('cantidad', models.IntegerField(blank=True, null=True)),
                ('estado_pago', models.CharField(max_length=80)),
                ('encargado', models.CharField(max_length=80)),
                ('descripcion', models.CharField(max_length=120)),
                ('id_evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='public.eventos')),
            ],
        ),
    ]
