# Generated by Django 3.1.2 on 2020-11-12 05:34

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0002_auto_20201111_1547'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paquete',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('categorizacion', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=80), size=None)),
                ('promociones', models.CharField(max_length=80)),
                ('categoria', models.CharField(max_length=80)),
                ('precio', models.FloatField()),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='public.evento')),
            ],
        ),
        migrations.AlterField(
            model_name='inscritos',
            name='id_paquete',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='public.paquete'),
        ),
        migrations.AlterField(
            model_name='preinscritos',
            name='id_paquete',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='public.paquete'),
        ),
        migrations.DeleteModel(
            name='Paquetes',
        ),
    ]
