# Generated by Django 3.1.2 on 2020-11-12 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0003_auto_20201112_0034'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividades',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('hora_inicio', models.DateTimeField()),
                ('ponente', models.CharField(max_length=80)),
                ('nombre', models.CharField(max_length=80)),
                ('hora_final', models.DateTimeField()),
                ('fecha', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Ambientes',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=80)),
                ('lugar', models.CharField(max_length=80)),
                ('cupos', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comite',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('lista_personal', models.CharField(max_length=80)),
                ('fecha_inicio', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='SubEventos',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=80)),
                ('estado', models.BooleanField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_final', models.DateField()),
                ('ambiente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='public.ambientes')),
                ('id_evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='public.evento')),
            ],
        ),
        migrations.RemoveField(
            model_name='egresos',
            name='id_evento',
        ),
        migrations.RemoveField(
            model_name='ingresos',
            name='id_evento',
        ),
        migrations.RemoveField(
            model_name='inscritos',
            name='id_asistente',
        ),
        migrations.RemoveField(
            model_name='inscritos',
            name='id_paquete',
        ),
        migrations.RemoveField(
            model_name='preinscritos',
            name='id_asistente',
        ),
        migrations.RemoveField(
            model_name='preinscritos',
            name='id_paquete',
        ),
        migrations.RemoveField(
            model_name='recibo',
            name='id_inscrito',
        ),
        migrations.DeleteModel(
            name='Asistentes',
        ),
        migrations.DeleteModel(
            name='Egresos',
        ),
        migrations.DeleteModel(
            name='Ingresos',
        ),
        migrations.DeleteModel(
            name='Inscritos',
        ),
        migrations.DeleteModel(
            name='Preinscritos',
        ),
        migrations.DeleteModel(
            name='Recibo',
        ),
        migrations.AddField(
            model_name='actividades',
            name='id_sub_evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='public.subeventos'),
        ),
    ]
