# Generated by Django 3.1.2 on 2020-11-11 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modulo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=80)),
                ('fecha_inicio', models.DateField()),
                ('fecha_final', models.DateField()),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='egresos',
            name='id_evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo.evento'),
        ),
        migrations.AlterField(
            model_name='ingresos',
            name='id_evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo.evento'),
        ),
        migrations.AlterField(
            model_name='paquetes',
            name='id_evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo.evento'),
        ),
        migrations.DeleteModel(
            name='Eventos',
        ),
    ]
