# Generated by Django 3.1.2 on 2020-12-03 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo', '0005_auto_20201112_1308'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipos', models.CharField(max_length=80)),
            ],
        ),
    ]
